// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCadKVIFSIwjq9VoJ_tihW87p26WS8MC9E',
    appId: '1:828208945452:web:8b85a8699cd5bfbb123489',
    messagingSenderId: '828208945452',
    projectId: 'huella6',
    authDomain: 'huella6.firebaseapp.com',
    storageBucket: 'huella6.firebasestorage.app',
    measurementId: 'G-8T5SL1SMSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXg4WmEqBaY1M_RW7DxEQ8tgdm-cSgiO8',
    appId: '1:828208945452:android:738f0c09cfb4ed62123489',
    messagingSenderId: '828208945452',
    projectId: 'huella6',
    storageBucket: 'huella6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAXhcj4KX0gctccWi5qGNN36h79_yKdao',
    appId: '1:828208945452:ios:a9ffcb036267c5f2123489',
    messagingSenderId: '828208945452',
    projectId: 'huella6',
    storageBucket: 'huella6.firebasestorage.app',
    iosBundleId: 'com.example.huella',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAXhcj4KX0gctccWi5qGNN36h79_yKdao',
    appId: '1:828208945452:ios:a9ffcb036267c5f2123489',
    messagingSenderId: '828208945452',
    projectId: 'huella6',
    storageBucket: 'huella6.firebasestorage.app',
    iosBundleId: 'com.example.huella',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCadKVIFSIwjq9VoJ_tihW87p26WS8MC9E',
    appId: '1:828208945452:web:704721d4a7da8646123489',
    messagingSenderId: '828208945452',
    projectId: 'huella6',
    authDomain: 'huella6.firebaseapp.com',
    storageBucket: 'huella6.firebasestorage.app',
    measurementId: 'G-QJ5NQKWDDH',
  );
}
